# Generated by Django 5.0.2 on 2024-02-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='statut',
            field=models.CharField(choices=[('Occuper', 'Occuper'), ('Libre', 'Libre')], default='Libre', max_length=10),
        ),
    ]
