# Generated by Django 5.0.2 on 2024-02-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_table_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casier',
            name='prix_achat_unitaire',
        ),
        migrations.AddField(
            model_name='entrestock',
            name='remise',
            field=models.FloatField(default=0),
        ),
    ]
